### ISSUE TITLE
Documentation says "get started above" but I see no get started above?

### ISSUE THREAD

**Issue by DaniloNovakovic** [enyancc/vscode-ext-color-highlight#151]
In Readme it says this:

![image](https://user-images.githubusercontent.com/24560296/140503229-91b32856-6503-4154-bb58-eefa6c3fa017.png)

but there is no button to click, especially confusing when I see it in VSCode:
![image](https://user-images.githubusercontent.com/24560296/140503285-406fa2d9-5e64-406c-901c-5f3961b25951.png)

**Comment by ferretwithaberet** [comment]
It means the "Get Started" entry in the VS Code command palette.
![image](https://user-images.githubusercontent.com/46427158/140603371-9de48b9c-c719-4a6b-9f85-746d4841d8e1.png)
