### ISSUE TITLE
question: does this extension work also on Monaco editor by itself?

### ISSUE THREAD

**Issue by giacomorebonato** [enyancc/vscode-ext-color-highlight#159]
Reading the FAQ of Monaco editor:
https://github.com/microsoft/monaco-editor/blob/903a92c7bb81f0e96301acfa7f79b09cc8f5ab88/README.md#faq

>❓ I've written an extension for VS Code, will it work on the Monaco Editor in a browser?
>No.
> Note: If the extension is fully based on the [LSP](https://microsoft.github.io/language-server-protocol/) and if the language server is authored in JavaScript, then it would be possible.

Is this extension a case fully based on LSP?

**Comment by ferretwithaberet** [comment]
No, this extension is not based on LSP at all.

**Comment by giacomorebonato** [comment]
Thanks, I'll look into LSP.
