### ISSUE TITLE
unreadable text hsl value

### ISSUE THREAD

**Issue by parham-dev27** [enyancc/vscode-ext-color-highlight#192]
Using background marker type, the text is not readable when the color is a dark color. The foreground color conversion does happen with rgb but not with hsl. So a color like: hsl(233, 47%, 7%) is not readable.

**Comment by wangyunduo** [comment]
Hello 👋 I notice that this repo has not had any new commits for the past year, and version 2.6.0, submitted last year, has not been released. Therefore, I forked the repo and developed a new extension based on version 2.6.0, named Color Highlight - Hue Show Better Version.

[Color Highlight - Hue Show Better Version](https://marketplace.visualstudio.com/items?itemName=Yunduo.color-highlight-css-color-4) can solve your issue. Feel free to try it out : )

**Comment by parham-dev27** [comment]
thanks mate
