### ISSUE TITLE
Pattern match for hex values

### ISSUE THREAD

**Issue by Jarrio** [enyancc/vscode-ext-color-highlight#30]
Just a small addition, is it possible to match for hex values?

![image](https://user-images.githubusercontent.com/748557/27980463-d5a13e6e-6376-11e7-9136-65665f56a838.png)

**Comment by sweggersen** [comment]
+1

**Comment by sweggersen** [comment]
#36

**Comment by ferretwithaberet** [comment]
Implemented in #45. This issue should've been closed.
