### ISSUE TITLE
sass variables with same x caracters, only first one is highlited

### ISSUE THREAD

**Issue by rchod** [enyancc/vscode-ext-color-highlight#34]
I hope this picture explains it all

![--capture du 2017-08-24 15-08-23](https://user-images.githubusercontent.com/623771/29667811-1f0253ae-88de-11e7-80c0-f380ea90a7c1.png)

**Comment by dorellango** [comment]
Same here 😿

**Comment by mattaningram** [comment]
I would also like this fixed.
