### ISSUE TITLE
Error: Document version already has changed

### ISSUE THREAD

**Issue by RandallFlagg** [enyancc/vscode-ext-color-highlight#44]
Hi,
In the console I always see: "Error: Document version already has changed"

What does it mean and how can I prevent it? (versions tested: 2.2.0, 2.3.0)

Thanks

**Comment by adamerose** [comment]
I'm writing another extension that inserts snippets using `vscode.window.activeTextEditor.insertSnippet` and it triggers this error in this extension. 

https://github.com/egonyans/vscode-ext-color-highlight/blob/315b80b3e1c44af41ef217b554b5e342b9ba6e0b/src/color-highlight.js#L99

**Comment by wenfangdu** [comment]
> I'm writing another extension that inserts snippets using `vscode.window.activeTextEditor.insertSnippet` and it triggers this error in this extension.
> 
> https://github.com/egonyans/vscode-ext-color-highlight/blob/315b80b3e1c44af41ef217b554b5e342b9ba6e0b/src/color-highlight.js#L99

I'm having the same issue when developing extensions, @ferretwithaberet could you please have a look at this?

**Comment by ferretwithaberet** [comment]
> > I'm writing another extension that inserts snippets using `vscode.window.activeTextEditor.insertSnippet` and it triggers this error in this extension.
> > 
> > https://github.com/egonyans/vscode-ext-color-highlight/blob/315b80b3e1c44af41ef217b554b5e342b9ba6e0b/src/color-highlight.js#L99
> 
> I'm having the same issue when developing extensions, @ferretwithaberet could you please have a look at this?

I've also noticed it, I will look upon it when I get to it, I got a lot of other stuff that I want to do to improve the extension.

**Comment by ferretwithaberet** [comment]
Seems like it is triggered by [this code](https://github.com/enyancc/vscode-ext-color-highlight/blob/2eb54c623027466badaf5810671361e10af4dbd1/src/color-highlight.js#L100-L103). It is catched by the `try {} catch () {}` block and outputted as a `console.error`. It seems to occur when you change the document contents after saving it. I could change it to a `console.log` to make it look less scary but it is nothing serious, I think it just prevents some code running unnecessarily.

**Comment by wenfangdu** [comment]
@ferretwithaberet Perhaps just change ` throw new Error('Document version already has changed');` to `return`? When developing extensions, I'm constantly seeing this message.
