### ISSUE TITLE
```json  { 	"activationTimes": { 		"startup": true, 		"codeLoadingTime": 55, 		"activateCallTime": 3, 		"activateResolvedTime": 0, 		"activationEvent": "*" 	} } ```

### ISSUE THREAD

**Issue by lahla81** [enyancc/vscode-ext-color-highlight#57]
- Extension Name: color-highlight
- Extension Version: 2.3.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by ferretwithaberet** [comment]
?
