### ISSUE TITLE
Maintain Project ?

### ISSUE THREAD

**Issue by GulajavaMinistudio** [enyancc/vscode-ext-color-highlight#87]
Is this project still maintained ? 
This is great project and useful extension. Hope you or any contributors can maintain it.

**Comment by ferretwithaberet** [comment]
> Time to fork?

I would fork it, but there is no `LICENSE` attached, so I do not know if I am able too. As far as I know, by default, you cannot modify or redistribute the code without explicit permission from the copyright holder.

**Comment by ferretwithaberet** [comment]
I contacted enyancc about this issue. I will now maintain this project. You are also welcome to contribute via pull requests!
